<?php
/**
 * OneDev_AdamVarga
 *
 * Copyright © 2024 - OneDev_AdamVarga. All rights reserved.
 * This file is part of a learning project created by Adam Varga for educational purposes.
 */
?>

<h1>Windy playground</h1>

<h1 class="mx-0 mt-0 mb-4 text-5xl font-bold text-gray-800 lg:mt-0 md:mt-32">
    Copy elements from any website as a Tailwind CSS component
</h1>

<p class="m-0 text-lg leading-7 text-blue-900">
    Speed up your workflow with Windy and save hours or even days when converting
    existing styles to Tailwind CSS.
</p>

<div class="flex flex-col mt-8 leading-6 text-black lg:flex-row sm:items-center">
    <button
        id="demoButton"
        class="hidden items-center py-3 px-4 mt-0 mr-4 mb-8 ml-0 text-base font-bold text-center text-gray-800 normal-case bg-gray-200 bg-none rounded-lg duration-150 ease-in-out cursor-pointer lg:mb-0 md:flex"
    >
        Try Windy on this site
    </button>
</div>

<img
    src="https://usewindy.com/img/transform_frame.svg"
    alt="Windy example"
    class="block max-w-full h-auto leading-6 text-black align-middle"
/>



