<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Develodesign\HyvaCmsWidgets\Block\Widget\Faq;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsSolid;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Escaper $escaper */
/** @var Faq $block */
/** @var ViewModelRegistry $viewModels */

$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$widgetTitle = $block->getData('faq_title');
$multiFieldSteps = $block->getMultiFieldSteps() ?: [];
$uniqueScriptId = crc32(uniqid());

?>

<div class="develo-faq-widget" itemscope itemtype="https://schema.org/FAQPage">
    <section class="bg-white dark:bg-gray-900">
        <div class="container px-6 py-12 mx-auto" x-data="{selected:<?= $uniqueScriptId . count($multiFieldSteps) ?>}">
            <h1 class="text-2xl font-semibold text-center text-gray-800 lg:text-4xl dark:text-white"><?= $widgetTitle ?></h1>
            <?php if (!empty($multiFieldSteps)) : ?>
            <ul class="mt-12 list-none">
                <?php foreach ($multiFieldSteps as $key => $question) :
                    $uniqueKey = $uniqueScriptId . $key;
                    $questionTitle = $question->getTitle();
                    $questionDescription = $question->getDescription();
                ?> 
                    <?php if ($questionTitle && $questionDescription) : ?>
                    <li class="relative border-b border-gray-200" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
                        <button type="button" class="px-8 py-6 w-full text-lg text-left" @click="selected !== <?= $uniqueKey ?> ? selected = <?= $uniqueKey ?> : selected = null">
                            <div class="flex justify-between items-center">
                                <span itemprop="name"><?= $question->getTitle() ?></span>
                                <span class="transition-all duration-700" x-bind:style="selected == <?= $uniqueKey ?> ? 'transform: rotate(180deg)' : ''">
                                    <?= $heroiconsSolid->chevronDownHtml() ?></span>
                            </div>
                        </button>

                        <div class="overflow-hidden relative max-h-0 transition-all duration-700" x-ref="container<?= $uniqueKey ?>" x-bind:style="selected == <?= $uniqueKey ?> ? 'max-height: ' + $refs.container<?= $uniqueKey ?>.scrollHeight + 'px' : ''">
                            <div class="px-10 border-t" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                                <span class="block py-4 w-full text-gray-700" itemprop="text"><?= $question->getDescription() ?></span>
                            </div>
                        </div>
                    </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
            <?php endif ?>
    </section>
</div>
<style>
    .max-h-0 {
        max-height: 0;
    }
</style>