<?php

/** @var Develodesign\HyvaCmsWidgets\Block\Widget\FeaturedImageBlock $block */

$multiSteps = $block->getSteps();
$limitedSteps = array_slice($multiSteps, 0, 4);
$stepCount = count($multiSteps);
$defaultLineColour = '#0AB6FF'; // Default
$margin = $block->getBlockMargin();

$itemWidths = [
    ['count' => 1, 'classes' => 'grid-cols-1'],
    ['count' => 2, 'classes' => 'sm:grid-cols-2 md:gap-x-14'],
    ['count' => 3, 'classes' => 'sm:grid-cols-2 md:grid-cols-3 lg:gap-x-14'],
    ['count' => 4, 'classes' => 'sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:gap-x-14'],
];

$checkCorrectItemCount = current(array_filter($itemWidths, function ($item) use ($limitedSteps) {
    return count($limitedSteps) == $item['count'];
}));

$getCorrectItemWidths = $checkCorrectItemCount['classes'];
?>

<div class="grid gap-12 justify-center my-12 <?= $getCorrectItemWidths ?>" style="<?= $margin ? 'margin: ' . $margin: '' ?>">
    <?php if ($multiSteps) : ?>
        <?php foreach ($limitedSteps as $steps) :
            $trimmedLineColour = trim($steps['line'], '#');
            $borderColour = $steps['line'] ? '#' . $trimmedLineColour : $defaultLineColour;
            $imageAlt = $steps['imagealt'] ?: 'Feature Image';
        ?>
            <div class="h-full bg-white shadow">
                <div class="feature-image">
                    <img class="w-full h-auto" style="border-bottom: 8px solid <?= $borderColour ?>" src="<?= $steps['image'] ?>" alt="<?= $imageAlt ?>" width="301" height="186">
                </div>
                <div class="p-8 feature-content">
                    <div class="mb-8 font-bold feature-title"><?= $steps['title'] ?></div>
                    <div class="leading-8 feature-text">
                        <?= htmlspecialchars_decode($steps['description']); ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>