<div class="flex relative flex-col justify-center items-center py-8 lg:py-14" style="background-image: url('<?php echo $block->getData('advert_contact_image'); ?>');
     background-color: <?php echo $block->getData('advert_bg_color'); ?>; background-repeat: no-repeat; background-size: cover; background-position: center;">
    <div class="absolute top-0 left-0 z-0 w-full h-full opacity-90 bg-brand-secondary"></div>
    <div class="flex z-10 items-center w-full">
        <div class="container">
            <div class="flex flex-col justify-between mx-10 text-black md:flex-row">
                <div class="flex flex-row">
                    <div>
                        <img src="<?php echo $block->getData('advert_icon_image'); ?>"class="hidden md:w-21 md:h-21 md:inline" viewBox="0 0 24.445 24.445">                           
                    </div>
                    <div class="mb-10 w-full text-center md:ml-5 md:text-left">
                        <div class="flex flex-wrap justify-center items-center mt-3 mb-3 md:block">
                            <img src="<?php echo $block->getData('advert_icon_image'); ?>" class="inline w-12 h-12 md:w-14 md:h-14 md:hidden" viewBox="0 0 24.453 24.445">                               
                            <h2 class="inline ml-2 text-5xl font-medium h2 md:ml-0"
                             style="color:<?php echo $block->getData('advert_title_color'); ?>"><?php echo $block->getData('advert_title'); ?></h2>
                        </div>
                        <p class="mx-auto mt-3 mb-5 text-xl body-default md:mt-0 md:mb-0 max-w-brand-230 md:max-w-full" 
                           style="color:<?php echo $block->getData('advert_content_color'); ?>"><?php echo $block->getData('advert_content'); ?></p>
                    </div>
                </div>
                <div class="flex flex-col justify-center items-center md:items-end">
                    <a href="<?php echo $block->getData('advert_button_url'); ?>"
                       style="margin: 5px 5px; padding: 20px 38px; border:0; border-radius:10px; font-weight:bold; background-color: <?php echo $block->getData('advert_button_color'); ?>;
                              color:<?php echo $block->getData('advert_button_text_color'); ?>;"><?php echo $block->getData('advert_button_text'); ?></a>
                </div>
            </div>

        </div>

    </div>
</div>



