<?php

$tabData = [];
$tabCount = 3;

foreach (range(1, $tabCount) as $index) {

    $quoteText = $block->getData('widgetquote-text-' . $index);

    if (isset($quoteText) && $quoteText !== '') {

        array_push($tabData, [
            'widgetquote-text' => $block->getData('widgetquote-text-' . $index),
            'widget-author' => $block->getData('widget-author-' . $index),
            'widget-company-name' => $block->getData('widget-company-name-' . $index),
        ]);
    }
}

$quoteCount = count($tabData);

?>

<?php if ($quoteCount) : ?>

    <div class="testimonials-container">

        <div class="mx-auto max-w-screen-xl">

            <div class="overflow-x-auto">

                <div class="flex flex-row flex-nowrap my-10 md:grid md:grid-cols-<?= $quoteCount ?> md:gap-0 lg:gap-28">

                    <?php foreach ($tabData as $tab) : ?>

                        <div class="min-w-[16.5rem] md:min-w-0 text-center px-6 md:px-7 lg:px-8 py-brand-90 md:py-26 flex flex-col flex-no-wrap justify-between">

                            <p class="quote block italic mb-8 text-[#100602] font-medium text-xl">
                                <?= $tab['widgetquote-text']; ?>
                            </p>

                            <p class="body-small text-[#100602]">
                                <?= $tab['widget-author']; ?>
                            </p>
                            <p class="font-light text-gray-700 body-small">
                                <?= $tab['widget-company-name']; ?>
                            </p>

                        </div>

                    <?php endforeach; ?>

                </div>

            </div>

        </div>

    </div>

<?php endif; ?>