<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element;
use Magento\Framework\Escaper;

/** @var Element $block  */
/** @var Escaper $escaper */
?>
<?= /** @noEs/workspace/magento-gitpod/app/code/Develocape */ $block->getElement()->getNote()->getText(); ?>
